/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gradle.cliapp.with.lib.template;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
